Repository carpentries/styles, pull requests merged in 2018-06, with the labels that each got.

#282 remove permalink that breaks asset includes
  CODE_OF_CONDUCT.md
Labels: bug

#243 Makefile: add docker-serve target
  Makefile
Labels: enhancement

#284 Add links.md to files in boilerplate
  bin/boilerplate/_episodes/01-introduction.md
  bin/boilerplate/_extras/about.md
  bin/boilerplate/_extras/discuss.md
  bin/boilerplate/_extras/figures.md
  bin/boilerplate/_extras/guide.md
Labels: enhancement

#298 add cp as carpentry lesson type (e.g. for instructor training)
  bin/boilerplate/_config.yml
  bin/lesson_check.py
Labels: type:enhancement

#313 _config.yml: fix link to the Library Carpentry website
  bin/boilerplate/_config.yml
Labels: type:bug

#318 added about the discussion stage to the LC description
  _includes/carpentries.html
Labels: type:enhancement
