Repository carpentries/styles, pull requests merged in 2021-03, with the labels that each got.

#559 Makefile: fix 'bundle config' command flags
  Makefile
Labels: type:template and tools

#565 Fix GitHub actions for lessons in Rmarkdown
  .github/workflows/template.yml
  .github/workflows/website.yml
Labels: high priority

#514 add class for images with a drop shadow
  assets/css/lesson.scss
Labels: status:waiting for response, type:template and tools
